### ISSUE TITLE
Need advice on implementing in Node.js

### ISSUE THREAD

**Issue by dmisadin** [raweceek-temeletry/f1-22-udp#8]
Hi, since I am new to programming I keep pushing keys until it just works, here is how I did it on node.js for browser based overlays. It works, but I am worried I am doing it the wrong way because performance is bad and sometimes it's lagging.

So server side index.js looks like this:

```
//F1 UDP Setup
const { F122UDP } = require("f1-22-udp");
const f122 = new F122UDP()
f122.start();

// Socket setup
const io = socket(server);

io.on("connection", function (socket) {
    console.log("Made socket connection");

    f122.on('lapData', function (data) {
        socket.broadcast.emit("lapData", data);
    })

    f122.on('participants', function (data) {
        socket.broadcast.emit("participants", data);
    })
});
```

Client side, where the overlays are made with JS/HTML/CSS, tower.js looks like this:
```
const socket = io();

socket.on("participants", function (data) {
    console.log(data);
});
socket.on("lapData", function (data) {
    console.log(data)
});
```
This is just an example, imagine there are functions being called instead of console.log.
I need advice on what is the best way to get the telemetry data to client side that is shown in browser because using socket to "re-emit" data from f1-22-udp to client seems redundant and is probably what makes my application lagg. It gets worse when I add more listeners for different events (lapData, participants, session, carStatus...).

**Comment by RobCoder44** [comment]
The game is quite data intensive so if you are also relaying that data out to socket connections in the browser, It's not great :/
Servers can handle the data no problem but a browser will throttle that amount of data coming in and on a mobile device will be like DDOS 😂☠

It will be better to use a database to store the data and a timer on the front end to request data from the server at intervals, EG every second rather than 50 data requests per second from sockets.

Just my advice and it works as I also do something like this 👍

**Comment by PrimeGoose** [comment]
try using less event emitters, ideally, there is only one in client side. you will need to combine all the data in one object server side.

**Comment by dmisadin** [comment]
These are both very good suggestions, thank you very much! I might try grouping events by update rate (there are some with 60Hz, some 2Hz etc.), but if that doesn't work out I will combine them.
I guess this qualifies as a solution so I will close the issue :)
